export class Municipality {
    public id_municipio = 0;
    public nombre_municipio = '';
    public numero_pedidos_municipio = 0;
    public numero_abonos = 0;
    public numero_facturas_municipio = 0;
    public numero_vendedores_municipio = 0;
    public numero_cobradores = 0;
    public numero_clientes_municipio = 0;
    public unidades_productos_pedidos_municipio = 0;
    public unidades_productos_vendidos_municipio = 0;
    public valor_pedido_municipio = 0;
    public valor_ventas_municipio = 0;
    public valor_abonado_municipio = 0;
    public valor_deuda_municipio = 0;
    public numero_cliente_municipio = 0;
    public departamento_municipio = 0;
    public latitud_municipio = 0;
    public longitud_municipio = 0;
}
